### ISSUE TITLE
Reproducing Question

### ISSUE THREAD

**Issue by ajskdlf64** [WenjinW/LATIN-Prompt#1]
Hey guys!

Very interesting topic and high quality paper from the research team.

After reading the paper and reproducing it with reference to the repository, I had a few questions that led me to raise an issue.

1. Is it correct that you used the boundingboxes of lines and the boundingboxes of texts in the original OCR provided by RRC leaderboard, and if so, was the performance not good when you used the boundingboxes of texts?

2. I was wondering if the ANLS values in your paper were calculated with your own code or the results you submitted to the RRC Leaderboard?

3. If the answer to 1 is LINE, is the overall process correct to use LINE OCR TEXT and TEXT_BOXES to get LAYOUT_RECOVER using SPACE_LAYOUT function and PROMPT_TASK to request GPT-3.5 API?

Thanks.

(P.S. There seems to be a typo in the title of the README.md :) Promot )

**Comment by WenjinW** [comment]
Thank you for your affirmation of our work and here are the explanations for related issues:
1. We used the bounding boxes of lines and the bounding boxes of texts (not words) in the original OCR information provided by the RRC leaderboard. We have not tested the performance of using text boxes. Compared with line text boxes, adjacent text boxes are more likely to overlap, which may affect the accuracy of calculating the number of spaces between adjacent texts. (Recently, we have tried different OCR tools and achieved better results, which will be provided in the new version of the paper.)
2. We used our own implementation to calculate the ANLS value on the validation set and used the results submitted to the RRC Leaderboard on the test set. 
3. Yes, we used LINE OCR TEXT and LINE TEXT_BOXES to get LAYOUT_RECOVER using SPACE_LAYOUT function and PROMPT_TASK to request GPT-3.5 API.

**Comment by WenjinW** [comment]
Here are the explanations for your questions:
1. The OCR results of DocVQA provided by the RRC leaderboard contain both [line level and word level information](https://github.com/WenjinW/LATIN-Prompt/blob/main/utils/docvqa.py#L156-L165).  We adopt the line level information in LAYOUT_RECOVER.
2. For users without a Claude account, we have provided an implementation based on Azure OpenAI GPT-3.5-turbo [here](https://github.com/WenjinW/LATIN-Prompt/blob/main/utils/openai_api.py). We add examples with GPT-3.5-turbo [here](https://github.com/WenjinW/LATIN-Prompt#examples-with-gpt-35-turbo). For more details about OpenAI, please refer to [here](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview).
3. The prompts provided above all look correct. It is noteworthy that:
a) When using GPT-3.5-turbo, please set the temperature to 0. Other settings can refer [here](https://github.com/WenjinW/LATIN-Prompt/blob/main/utils/openai_api.py). 
b) You can use the [anls.py](https://github.com/WenjinW/LATIN-Prompt/blob/main/metric/anls.py) we provide to calculate the score. Note that since it is easy to encounter network problems when accessing the API, we regularly store the predicted results and support [reading the stored result files](https://github.com/WenjinW/LATIN-Prompt/blob/main/examples/claude_docvqa.py#L203) when restarting the experiment to continue predicting subsequent samples. Therefore, when starting a new experiment, please delete the old result file or distinguish the experiments with different experiment names. 

Hope the above content is helpful to you and please feel free to discuss them further.

**Comment by ajskdlf64** [comment]
Thanks for the update! When I run the script below, I get the following error, what is the solution?

```bash
bash script/claude_eval.sh 0 gpt-35 docvqa task_instruction_space
```
```bash
Traceback (most recent call last):
  File "examples/claude_docvqa.py", line 22, in <module>
    from utils import claude, space_layout, openai_api
  File "./utils/claude.py", line 6, in <module>
    c = anthropic.Client(os.environ["ANTHROPIC_API_KEY"])
  File "/root/anaconda3/envs/cream/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'ANTHROPIC_API_KEY'
```

**Comment by ajskdlf64** [comment]
I am experiencing difficulties in reproducing your paper using the official Python OpenAI library. The reproduction process is not functioning correctly. I have a few questions and concerns regarding this matter:

I have found that your experiment can be successfully reproduced using the MS Azure OpenAI endpoint, but not with the official Python OpenAI library. Can you provide any insight into this discrepancy?

According to the OPENAI API Reference, the "completions" parameter is only applicable to older models such as "text-davinci-003." The model you utilized, "gpt-3.5-turbo," should use "chatCompletions" instead of "completions." Could you clarify why this difference exists?

Additionally, it appears that the correct model name is "gpt-3.5-turbo" (with a hyphen), not "gpt-35-turbo" as mentioned in the paper. Moreover, the argument to use in the chat completion should be "model" instead of "engine," as indicated in the latest version of the library. Can you confirm these changes?

I attempted to reproduce the provided example using "gpt-3.5-turbo" and the official OpenAI library. However, the performance I achieved on the test dataset was 0.58. Could you offer any insights into why my results differ from yours?

Have you attempted to reproduce the experiment using the official OpenAI library? I'm curious to know if the "LATIN-prompt" used in your paper might be overfitted to the MS Azure OpenAI model.

PS.1) Reproducing the execution by running the script in the main branch is challenging due to dependencies like "wandb." It would be greatly appreciated if you could address this aspect as well.

PS.2) My goal is to successfully reproduce your research and achieve a score of 0.81 for submission to RRC. 

Your innovative and groundbreaking work has left a strong impression on me. I truly value your prompt responses and kind explanations.

Thanks.

**Comment by ajskdlf64** [comment]
I understood this to mean to use the official OPENAI API, as a combination of "gpt-3.5-turbo" and "completions".

However, that combination is no longer supported by the official.

I've implemented openai_completion and openai_chat_completion like below by referring to LATIN's code.

When using "gpt-3.5-turbo", "openai_completions" throws an error, and when using "openai_chat_completions", a performance score of 0.58 was recorded.

![image](https://github.com/WenjinW/LATIN-Prompt/assets/41967014/d5aabd9b-dc26-4642-8c80-519e7c6db95c)

```python
import openai
openai.api_key = "---"

def openai_completion(prompt):

    while True:
        try:
            response = openai.Completion.create(
                model="gpt-3.5-turbo",
                prompt=prompt,
                max_tokens=200,
                temperature=0,
                stop="\n\n",
            )
            text = response['choices'][0]['text']
            break
        except TypeError:
            print(f"TypeError, maybe the prompt is too long: {len(prompt)}. Redeucing the prompt length.")
            if len(prompt) > 4000:
                question_idx = prompt.rfind("\n\nQuestion:")
                prompt = prompt[:4000-len(prompt[question_idx:])] + prompt[question_idx:]
            else:
                question_idx = prompt.rfind("\n\nQuestion:")
                prompt = prompt[:question_idx-300] + prompt[question_idx:]
            continue

    return text

def openai_chat_completion(prompt):

    messages = [{
        "role": "user",
        "content": prompt,
    }]
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages,
        max_tokens=200,
        temperature=0,
        stop="\n\n",
    )
    text = response['choices'][0]['message']['content']

    return text
```

#### completions
```python
openai_completion(prompt="Write a tagline for an ice cream shop. ")
```
```python
InvalidRequestError: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
```

### chatCompletions
```python
openai_chat_completion(prompt="Write a tagline for an ice cream shop. ")
```
```python
'"Scoops of happiness in every cone!"'
```

**Comment by WenjinW** [comment]
We are trying to adapt LATIN-Prompt to the latest `chatCompletions` interface and analyze the differences between it and the `completions` interface. An alternative approach to verifying the effect of LATIN-Prompt is to use older models like `text-davinci-003`.

Thank you for your support of our project. We will give you feedback as soon as we complete the adaptation.

**Comment by WenjinW** [comment]
@ajskdlf64 Hello, we recently tried the `chatCompletions` with the LATIN-Prompt and the result was around 0.58. We also conducted some preliminary experiments and found that the `system message` has a significant impact on the experimental results. We believe that the difference in performance between `chatCompletions` and `completions` is mainly due to the `system message`, while our method does not take into account the impact of it. We are analyzing the differences in prompts between `system message` and `user content`. You can also try some attempts from this perspective.

**Comment by ajskdlf64** [comment]
I commend the authors for their dedicated research and passion. I have indeed noticed that the performance can vary depending on the version and usage of OpenAI's API.

I encourage further research to advance into higher-quality papers.

Thank you!
